In [1]:
np.import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)


array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[3,4,2],[4,6,3]]
my_matrix

[[1, 2, 3], [3, 4, 2], [4, 6, 3]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [3, 4, 2],
       [4, 6, 3]])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
 np.zeros((10,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(int(input("enter a value")))

enter a value4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(int(input("enter the value ")))

enter the value 4


array([0.23603753, 0.74305819, 0.45724816, 0.63843725])

In [29]:
np.random.rand(3)

array([0.65092591, 0.70156493, 0.87889092])

In [31]:
np.random.rand(int(input("enter the value "))),(int(input("enter the value ")))

enter the value 5
enter the value 5


(array([0.65992145, 0.61234802, 0.41133719, 0.50924223, 0.72839829]), 5)

In [34]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [43]:
ranarr

array([12, 25,  8, 14,  2, 32,  0, 19,  8,  4])

In [44]:
ranarr.min()

0

In [41]:
ranarr.max()

32

In [45]:
ranarr.argmax()

5

In [46]:
ranarr.argmin()

6

# program

In [47]:
import numpy as ds

In [51]:
ds.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
ds.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
ds.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [57]:
d=ds.arange(10,50)


In [58]:
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
d=(int(input("enter first range "))(input("enter last range")))
d=ds.arange(a,b)
print(d)